export const NUM_OF_TRACKS = 20
export const SELECTED_YEAR = 2019
export const SELECTED_MONTH = 5
export const START_DAY = 1
export const SELECTED_NUM_OF_DAYS = 2
export const HOURS_PER_DAY = 24
export const NUM_OF_HOURS = SELECTED_NUM_OF_DAYS * HOURS_PER_DAY
export const MAX_HOUR_SPAN = 16
export const MIN_HOUR_SPAN = 2
export const MAX_TRACK_START_GAP = 4
export const MAX_ELEMENT_GAP = 16
export const MAX_NUM_OF_SUBTRACKS = 10
